service: import-service
frameworkVersion: '3'

useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - s3:*
      Resource:
        - 'arn:aws:s3:::uploaded-service/*'
  environment:
    REGION: ${env:REGION}
    BUCKET_NAME: ${env:BUCKET_NAME}

functions:
  importProductsFile:
    handler: functions/importProductsFile.handler
    events:
      - httpApi:
          path: /import
          method: GET
  importFileParser:
    handler: functions/importFileParser.handler
    events:
      - s3:
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true # enable auto-packing of external modules
